"""Parse country PDFs under `output/<Continent>/<Country>.pdf` into structured
JSON files under `json/<Continent>/<Country>.json`, plus a `json/index.json`
manifest listing continents and their countries.

The PDFs were generated by `getCountryData.py` from a known JSON schema, so
each PDF has the same section labels in the same order. This script reverses
that process using text extraction (no OCR needed - PDFs contain a real text
layer).

Usage:
    python pdf_to_json.py
"""

import ast
import glob
import json
import os
import re
import unicodedata

import pdfplumber

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(ROOT_DIR, "output")
JSON_DIR = os.path.join(ROOT_DIR, "json")

# Section label -> key in the resulting JSON, in the order they appear in the PDF.
SECTIONS = [
    ("Continent:", "continent"),
    ("Languages Spoken:", "languages"),
    ("Population:", "population"),
    ("Currency:", "currency"),
    ("Area:", "area"),
    ("Main Landmarks:", "landmarks"),
    ("Head of State / Government:", "head_of_state"),
    ("Main Cultural Events:", "cultural_events"),
    ("Food & Cuisine:", "food_writeup"),
    ("Brief History:", "brief_history"),
    ("Important People:", "important_people"),
    ("Current Conflicts:", "current_conflicts"),
    ("Youtube Links:", "five_youtube_video_titles"),
]

LIST_KEYS = {
    "landmarks",
    "cultural_events",
    "important_people",
    "five_youtube_video_titles",
}

DICT_LIST_KEYS = {"landmarks", "cultural_events"}


def extract_text(pdf_path: str) -> str:
    with pdfplumber.open(pdf_path) as pdf:
        pages = [page.extract_text() or "" for page in pdf.pages]
    return "\n".join(pages)


def split_sections(text: str) -> tuple:
    """Returns (title, raw_sections). `title` is the country name as printed
    in the PDF (the first line, before any recognized section label) - this
    is the authoritative spelling/accents, unlike the sanitized filename."""
    lines = text.split("\n")

    label_positions = []
    for i, line in enumerate(lines):
        stripped = line.strip()
        for label, key in SECTIONS:
            if stripped == label or stripped.startswith(label):
                label_positions.append((i, label, key, stripped[len(label):].strip()))
                break

    title_end = label_positions[0][0] if label_positions else 0
    title = " ".join(l.strip() for l in lines[:title_end] if l.strip())

    raw = {}
    for idx, (line_no, label, key, inline_value) in enumerate(label_positions):
        end = label_positions[idx + 1][0] if idx + 1 < len(label_positions) else len(lines)
        body_lines = lines[line_no + 1:end]
        if inline_value:
            body_lines = [inline_value] + body_lines
        raw[key] = body_lines
    return title, raw


def join_wrapped_paragraph(body_lines: list) -> str:
    return " ".join(l.strip() for l in body_lines if l.strip())


def parse_bullet_items(body_lines: list) -> list:
    """Group wrapped lines into bullet items starting with '- '."""
    items = []
    current = []
    for line in body_lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("- "):
            if current:
                items.append(" ".join(current))
            current = [stripped[2:].strip()]
        else:
            current.append(stripped)
    if current:
        items.append(" ".join(current))
    return items


def parse_dict_or_string(item: str):
    """Bullet item may be a Python-dict repr (from str(dict) in source data)
    like "{'name': 'X', 'writeup': 'Y'}", or a plain string."""
    if item.startswith("{") and item.endswith("}"):
        try:
            parsed = ast.literal_eval(item)
            if isinstance(parsed, dict):
                return {
                    "name": parsed.get("name", "").strip(),
                    "writeup": parsed.get("writeup", "").strip(),
                }
        except (ValueError, SyntaxError):
            pass
    return {"name": item, "writeup": ""}


def parse_person(item: str) -> dict:
    """Important people are either "Name - description" or just "Name"."""
    if " - " in item:
        name, desc = item.split(" - ", 1)
        return {"name": name.strip(), "description": desc.strip()}
    return {"name": item.strip(), "description": ""}


def build_country_json(pdf_path: str, continent_from_folder: str) -> dict:
    fallback_name = os.path.splitext(os.path.basename(pdf_path))[0]
    text = extract_text(pdf_path)
    title, raw = split_sections(text)

    data = {"country": title or fallback_name}

    for label, key in SECTIONS:
        body_lines = raw.get(key, [])
        if key in DICT_LIST_KEYS:
            data[key] = [parse_dict_or_string(i) for i in parse_bullet_items(body_lines)]
        elif key == "important_people":
            data[key] = [parse_person(i) for i in parse_bullet_items(body_lines)]
        elif key == "five_youtube_video_titles":
            data[key] = parse_bullet_items(body_lines)
        elif key == "languages":
            joined = join_wrapped_paragraph(body_lines)
            data[key] = [s.strip() for s in joined.split(",") if s.strip()]
        else:
            data[key] = join_wrapped_paragraph(body_lines)

    # The folder name is authoritative for continent (matches countries.csv).
    data["continent"] = continent_from_folder
    return data


def safe_slug(name: str) -> str:
    """URL/filename-friendly kebab-case id, e.g. "Côte d'Ivoire" -> "cote-divoire"."""
    normalized = unicodedata.normalize("NFKD", name)
    ascii_only = normalized.encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^A-Za-z0-9]+", "-", ascii_only).strip("-").lower()
    return slug or "unnamed"


def main():
    os.makedirs(JSON_DIR, exist_ok=True)
    continent_folders = sorted(
        d for d in glob.glob(os.path.join(OUTPUT_DIR, "*")) if os.path.isdir(d)
    )

    index = {"continents": []}

    for continent_dir in continent_folders:
        continent = os.path.basename(continent_dir)
        pdf_files = sorted(glob.glob(os.path.join(continent_dir, "*.pdf")))
        out_dir = os.path.join(JSON_DIR, continent)
        os.makedirs(out_dir, exist_ok=True)

        countries = []
        for pdf_path in pdf_files:
            data = build_country_json(pdf_path, continent)
            country_name = data["country"]
            slug = safe_slug(country_name)
            out_path = os.path.join(out_dir, f"{slug}.json")
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            countries.append({"name": country_name, "slug": slug})
            print(f"Wrote {out_path}")

        countries.sort(key=lambda c: c["name"])
        index["continents"].append(
            {
                "name": continent,
                "slug": safe_slug(continent),
                "countryCount": len(countries),
                "countries": countries,
            }
        )

    index["continents"].sort(key=lambda c: c["name"])
    with open(os.path.join(JSON_DIR, "index.json"), "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=2)
    print(f"Wrote {os.path.join(JSON_DIR, 'index.json')}")


if __name__ == "__main__":
    main()
